# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: virtualenv ./venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - run: source .env
      - run: pytest

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
