# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# echo 'export PATH=~PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.0

    steps:
      - checkout
      # - run: python -m venv venv
      # - run: source venv/bin/activate
      - run: /usr/local/bin/python -m pip install --upgrade pip
      - run: 
          command: |
            echo 'export PATH=~PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run: source .env
      - run: pytest

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
